In [72]:
import pandas as pd
from datetime import datetime
from sklearn import preprocessing

In [85]:
df1 = pd.read_csv("../data/original/online_shoppers_intention.csv")
target1 = 'Revenue'
# Fixing Online Shopping Intention Dataset

# ORDINALENCODING CATEGORICAL FEATURES
df1[target1] = df1[target1].astype(int)

d = {'Jan':1, 'Feb':2, 'Mar':3, 'Apr':4, 'May':5, 'June':6, 'Jul':7, 'Aug':8, 'Sep':9, 'Oct':10, 'Nov':11, 'Dec':12}
df1['Month'] = df1['Month'].map(d)

df1['Weekend'] = df1['Weekend'].astype(int)

d = {'New_Visitor':0, 'Returning_Visitor':1, 'Other':2}
df1['VisitorType'] = df1['VisitorType'].map(d)

# STANDARDIZING NUMERICAL FEATURES
numerical_features = ["Administrative", "Administrative_Duration", "Informational", "Informational_Duration", 
                      "ProductRelated", "ProductRelated_Duration", "BounceRates", "ExitRates", "PageValues", "SpecialDay"]
scaler = preprocessing.StandardScaler().fit(df1[numerical_features])
df1[numerical_features] = scaler.transform(df1[numerical_features])

# SAVING
df1.to_csv('../data/processed/online_shoppers_intentions.csv')
df1

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,-0.696993,-0.457191,-0.396478,-0.244931,-0.691003,-0.624348,3.667189,3.229316,-0.317178,-0.308821,2,1,1,1,1,1,0,0
1,-0.696993,-0.457191,-0.396478,-0.244931,-0.668518,-0.590903,-0.457683,1.171473,-0.317178,-0.308821,2,2,2,1,2,1,0,0
2,-0.696993,-0.457191,-0.396478,-0.244931,-0.691003,-0.624348,3.667189,3.229316,-0.317178,-0.308821,2,4,1,9,3,1,0,0
3,-0.696993,-0.457191,-0.396478,-0.244931,-0.668518,-0.622954,0.573535,1.994610,-0.317178,-0.308821,2,3,2,2,4,1,0,0
4,-0.696993,-0.457191,-0.396478,-0.244931,-0.488636,-0.296430,-0.045196,0.142551,-0.317178,-0.308821,2,3,3,1,4,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,0.206173,0.363075,-0.396478,-0.244931,0.478227,0.307822,-0.310366,-0.288966,0.342125,-0.308821,12,4,6,1,1,1,1,0
12326,-0.696993,-0.457191,-0.396478,-0.244931,-0.601062,-0.380957,-0.457683,-0.447364,-0.317178,-0.308821,11,3,2,1,8,1,1,0
12327,-0.696993,-0.457191,-0.396478,-0.244931,-0.578577,-0.528063,1.261014,0.897093,-0.317178,-0.308821,11,3,2,1,13,1,1,0
12328,0.507228,-0.032916,-0.396478,-0.244931,-0.376210,-0.443536,-0.457683,-0.453140,-0.317178,-0.308821,11,2,2,3,11,1,0,0
12329,-0.696993,-0.457191,-0.396478,-0.244931,-0.646033,-0.613243,-0.457683,0.485525,-0.317178,-0.308821,11,3,2,1,2,0,1,0

In [91]:
df2 = pd.read_csv("../data/original/marketing_campaign.csv", sep='\t')
target2 = 'Teenhome'

# Fixing Marketing Campaign Dataset

# Z_CostContact and Z_Revenue never change, therefore they are not good features for prediction.
df2 = df2.drop(columns=['Z_CostContact','Z_Revenue'])

# Filling empty instances
df2 = df2.fillna(df2['Income'].mean())

# Converting date to day_count variable
first = datetime(2012,7,30,0,0,0)
temp = []
for value in df2['Dt_Customer']:
    date = value.split('-')
    this = datetime(int(date[2]), int(date[1]), int(date[0]), 0, 0, 0)
    temp.append((this-first).days)
df2['Dt_Customer'] = temp

# Regrouping Marital Status
df2['Marital_Status'] = df2['Marital_Status'].map({'Married':'Married','Together':'Together','Single':'Single','Divorced':'Divorced','Widow':'Widow','Alone': 'Single', 'YOLO':'Unknown', 'Absurd':'Unknown'})

# ORDINALENCODING CATEGORICAL FEATURES

df2[target2] = df2[target2].replace([1,2], 1)

d = {'Unknown':0, 'Widow':1, 'Divorced':2, 'Single':3, 'Together':4, 'Married':5}
df2['Marital_Status'] = df2['Marital_Status'].map(d)

d = {'Basic':0, 'Graduation':1, '2nd Cycle':2, 'Master':3, 'PhD':4}
df2['Education'] = df2['Education'].map(d)


# STANDARDIZING NUMERICAL FEATURES
numerical_features = ['Income','MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 
                      'MntGoldProds', 'Year_Birth','Recency','NumDealsPurchases','NumWebPurchases','NumCatalogPurchases',
                      'NumStorePurchases','NumWebVisitsMonth','Dt_Customer']
scaler = preprocessing.StandardScaler().fit(df2[numerical_features])
df2[numerical_features] = scaler.transform(df2[numerical_features])

# SAVING
df2.to_csv('../data/processed/marketing_campaign.csv')
df2['Education'].value_counts()

3.0    486
2.0    370
0.0     54
Name: Education, dtype: int64

In [79]:
df3 = pd.read_csv("../data/original/heart.csv")
target3 = 'target'

# Fixing Heart Dataset

#print( df3[target3].value_counts() )

df3

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0